using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace FunnyLanguage_WPF
{
    /// <summary>
    /// code generated by chatgpt
    /// </summary>
    public class TextChecker
    {
        public bool CheckText(string text1, string text2)
        {
            // Remove extra spaces and make the text lowercase for comparison
            string normalizedText1 = NormalizeText(text1).Trim();
            string normalizedText2 = NormalizeText(text2).Trim();

            // Perform a case-insensitive comparison
            return string.Equals(normalizedText1, normalizedText2, StringComparison.OrdinalIgnoreCase);
        }

        public string NormalizeText(string text)
        {
            // Remove extra spaces using regular expression
            string normalizedText = Regex.Replace(text, @"\s+", " ");

            // Convert the text to lowercase
            normalizedText = normalizedText.ToLower();

            return normalizedText;
        }
    }
}
